server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: block-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.126.204:3306/block-page?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: notbadkimkimjung

  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

kakao:
  pay:
    api:
      key: b5eab0583f764211dca02952c891b3ba
      content-type: application/x-www-form-urlencoded;charset=utf-8
      url: https://kapi.kakao.com