server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone }https://github.com/N0T-BAD/BE-block/blob/develop/src/main/resources/application-prod.yml

spring:
  application:
    name: block-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  redis:
    host: host.docker.internal
    port: 6379

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

feign:
  client:
      config:
          default:
              connectTimeout: 5000
              readTimeout: 5000

kakao:
  pay:
    api:
      key: ${kakao.pay.api.key}
      url: ${kakao.pay.api.url}
      content-type: application/x-www-form-urlencoded;charset=utf-8
